# Copyright (C) 2023  Nicolas Möser

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from ..general import ui_positions
from ..general import buttons
import pyautogui

MENU_DICT = {
    'Ground 1': pyautogui.Point(*ui_positions.MENU_SLOT01),
    'Ground 2': pyautogui.Point(*ui_positions.MENU_SLOT02),
    'Ground 3': pyautogui.Point(*ui_positions.MENU_SLOT03),
    'Brush': pyautogui.Point(*ui_positions.MENU_SLOT04),
    'Foliage': pyautogui.Point(*ui_positions.MENU_SLOT05),
    'Roads': pyautogui.Point(*ui_positions.MENU_SLOT06),
    "Walls/Fences": pyautogui.Point(*ui_positions.MENU_SLOT07),
    "Modular Buildings": pyautogui.Point(*ui_positions.MENU_SLOT08),
    "Independent Buildings": pyautogui.Point(*ui_positions.MENU_SLOT09),
    "Flavor Objects 1": pyautogui.Point(*ui_positions.MENU_SLOT10),
    "Flavor Objects 2": pyautogui.Point(*ui_positions.MENU_SLOT11),

    'Dirt': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Dirt Red': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Hard': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Rocky': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Rocky Red': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Sand': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Grass': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Grass Y': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Clover': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Flowers': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Grass T': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Grass TY': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Weeds': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Grass XT': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Lt Forest': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Hvy Forest': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Mud': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Marsh': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Water': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Shallow Ford': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Deep Ford': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Pavement 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Pavement 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Cobblestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Gravel': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Dirt Lot': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Plow NS': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Plow EW': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Crop 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Crop 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Crop 3': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Crop 4': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),
    
    'Crop 5': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Crop 6': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),

    'Brush_brush': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),

    'Tree A': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Tree B': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Tree C': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Tree D': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    'Tree E': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),
    'Bush A': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_3),
    'Bush B': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_3),
    'Bush C': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_3),

    'density 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'density 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'density 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'density 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),

    'Dirt Road': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Gravel Road': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Paved 1': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Paved 2': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    'Foot Path': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),
    'Railroad': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_3),
    'Stream': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_3),
    'Highway': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_3),

    'Road Tile 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Road Tile 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Road Tile 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Road Tile 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Road Tile 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Road Tile 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Road Tile 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),
    'Road Tile 8': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_3),
    'Road Tile 9': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_3),
    'Road Tile 10': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_4),
    'Road Tile 11': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_4),
    'Road Tile 12': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_4),

    'Direction 1': buttons.DIRECTION_1,
    'Direction 2': buttons.DIRECTION_2,
    'Direction 3': buttons.DIRECTION_3,
    'Direction 4': buttons.DIRECTION_4,

    'Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Tall Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Brick': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Tall Brick': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Rural Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Hedge': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Bocage': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Low Bocage': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Wood Fence': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Wire Fence': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),

    '1 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    '2 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    '3 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    '4 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    '5 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),
    '6 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_3),
    '7 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_3),
    '8 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_3),

    'Building 1': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_1),
    'Building 2': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_1),
    'Building 3': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_1),
    'Building 4': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_1),
    'Building 5': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_2),
    'Building 6': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_2),
    'Building 7': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_2),
    'Building 8': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_2),
    'Building 9': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_3),
    'Building 10': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_3),
    'Building 11': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_3),
    'Building 12': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_3),
    'Building 13': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_4),
    'Building 14': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_4),
    'Building 15': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_4),
    'Building 16': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_4),

    'House': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Commercial': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Barn': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Church': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    'Other': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),

    'Commercial 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Commercial 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Commercial 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Commercial 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Commercial 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Commercial 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Commercial 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),
    'Commercial 8': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_3),
    'Commercial 9': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_3),

    'Barn 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Barn 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Barn 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Barn 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Barn 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Barn 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),

    'Church 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Church 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Church 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Church 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),

    'Other 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Other 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Other 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Other 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Other 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Other 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Other 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),

    'Barrel': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Bench': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Bin': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Crate': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Drum': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Farm': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Fountain': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Fountain Lrg': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Garden': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Gravestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Hand Cart': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Haystack': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Junk': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Log': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Manhole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Milestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Pole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Pond': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Poster': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Roadside': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Rock': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Sack': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Shed': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Shelter': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Strt Lamp': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Strt Sign': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Stump': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Tel Pole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Tire': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Woodpile': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),

    'Object 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Object 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Object 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Object 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Object 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Object 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Object 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),
    'Object 8': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_3),
    'Object 9': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_3),
}
