# Copyright (C) 2023  Nicolas Möser

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from ..general import ui_positions
from ..general import buttons
import pyautogui

MENU_DICT = {
    'Ground 1': pyautogui.Point(*ui_positions.MENU_SLOT01),
    'Ground 2': pyautogui.Point(*ui_positions.MENU_SLOT02),
    'Ground 3': pyautogui.Point(*ui_positions.MENU_SLOT03),
    'Brush': pyautogui.Point(*ui_positions.MENU_SLOT04),
    'Foliage': pyautogui.Point(*ui_positions.MENU_SLOT05),
    'Roads': pyautogui.Point(*ui_positions.MENU_SLOT06),
    "Walls/Fences": pyautogui.Point(*ui_positions.MENU_SLOT07),
    "Modular Buildings": pyautogui.Point(*ui_positions.MENU_SLOT08),
    "Independent Buildings": pyautogui.Point(*ui_positions.MENU_SLOT09),
    "Flavor Objects 1": pyautogui.Point(*ui_positions.MENU_SLOT10),
    "Flavor Objects 2": pyautogui.Point(*ui_positions.MENU_SLOT11),
    "Flavor Objects 3": pyautogui.Point(*ui_positions.MENU_SLOT12),

    'Dirt': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Dirt Red': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Hard': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Rocky': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Rocky Red': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Heavy Rocks': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Sand': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Grass': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Grass Y': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Clover': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Flowers': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Grass T': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Grass TY': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Weeds': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Grass XT': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Grass XTY': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Lt Forest': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Hvy Forest': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Mud': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Marsh': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Depp Marsh': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Water': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Reeds': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Shallow Ford': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Deep Ford': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Pavement 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Pavement 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Cobblestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Gravel': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Dirt Lot': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Plow NS': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Plow EW': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Crop 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Crop 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Crop 3': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Crop 4': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Crop 5': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Crop 6': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),

    'Brush_brush': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),

    'Tree A': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Tree B': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Tree C': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Tree D': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    'Tree E': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),
    'Tree F': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_3),
    'Tree G': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_3),
    'Tree H': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_3),
    'Bush A': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_4),
    'Bush B': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_4),
    'Bush C': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_4),

    'density 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'density 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'density 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'density 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),

    'Dirt Road': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Gravel Road': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Paved 1': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Paved 2': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),
    'Foot Path': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_2),
    'Railroad': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_3),
    'Stream': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_3),
    'Highway': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_3),

    'Road Tile 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Road Tile 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Road Tile 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Road Tile 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Road Tile 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Road Tile 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Road Tile 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),
    'Road Tile 8': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_3),
    'Road Tile 9': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_3),
    'Road Tile 10': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_4),
    'Road Tile 11': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_4),
    'Road Tile 12': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_4),

    'Direction 1': buttons.DIRECTION_1,
    'Direction 2': buttons.DIRECTION_2,
    'Direction 3': buttons.DIRECTION_3,
    'Direction 4': buttons.DIRECTION_4,

    'Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Tall Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Brick': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Tall Brick': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Rural Stone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Hedge': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Low Bocage': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Wood Fence': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Wire Fence': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Picket': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Sticks': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),

    '1 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    '2 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    '3 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    '4 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    '5 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    '6 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    '7 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    '8 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    '9 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    '10 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    '11 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    '12 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    '13 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    '14 Story': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),

    'Building 1': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_1),
    'Building 2': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_1),
    'Building 3': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_1),
    'Building 4': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_1),
    'Building 5': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_2),
    'Building 6': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_2),
    'Building 7': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_2),
    'Building 8': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_2),
    'Building 9': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_3),
    'Building 10': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_3),
    'Building 11': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_3),
    'Building 12': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_3),
    'Building 13': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_4),
    'Building 14': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_4),
    'Building 15': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_4),
    'Building 16': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_4),

    'House': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_1),
    'Commercial': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_3_1),
    'Barn': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_1_2),
    'Church': pyautogui.Point(*ui_positions.SUB_MENU_1_3x4_2_2),

    'Commercial 1': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_1),
    'Commercial 2': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_1),
    'Commercial 3': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_1),
    'Commercial 4': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_1),
    'Commercial 5': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_2),
    'Commercial 6': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_2),
    'Commercial 7': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_2),
    'Commercial 8': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_2),
    'Commercial 9': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_3),
    'Commercial 10': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_3),
    'Commercial 11': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_3),
    'Commercial 12': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_3),
    'Commercial 13': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_4),
    'Commercial 14': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_4),
    'Commercial 15': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_4),
    'Commercial 16': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_4),

    'Barn 1': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_1),
    'Barn 2': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_1),
    'Barn 3': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_1),
    'Barn 4': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_1),
    'Barn 5': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_2),
    'Barn 6': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_2),
    'Barn 7': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_2),
    'Barn 8': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_2),
    'Barn 9': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_3),
    'Barn 10': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_3),
    'Barn 11': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_3),
    'Barn 12': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_3),
    'Barn 13': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_4),
    'Barn 14': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_4),
    'Barn 15': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_4),
    'Barn 16': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_4),

    'Church 1': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_1),
    'Church 2': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_1),
    'Church 3': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_1),
    'Church 4': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_1),
    'Church 5': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_2),
    'Church 6': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_2),
    'Church 7': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_2),
    'Church 8': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_2),
    'Church 9': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_3),
    'Church 10': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_3),
    'Church 11': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_3),
    'Church 12': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_3),
    'Church 13': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_1_4),
    'Church 14': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_2_4),
    'Church 15': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_3_4),
    'Church 16': pyautogui.Point(*ui_positions.SUB_MENU_2_4x4_4_4),

    'AirCon': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'ATM': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Barrel': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Barrier': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Bench': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Bin': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Cart': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Crate': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Drum': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Farm 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Farm 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Fountain': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Fountain Lrg': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Garden': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Gravestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Hand Cart': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Haystack': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Junk': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Log': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Manhole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Milestone': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Monument': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Pallet': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Plant': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Pole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Pond': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Poster': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Road Sgn 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Roadside': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),
    'Roadside 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_4),
    'Rock': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_4),
    'Sack': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_4),

    'Shed': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_1),
    'Shelter': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_1),
    'Stove': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_1),
    'Strt Lamp': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_1),
    'Strt Lt 1': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_2),
    'Strt Lt 2': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_2),
    'Strt Sign': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_2),
    'Stump': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_2),
    'Tel Pole': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_3),
    'Tire': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_2_3),
    'Traf Lt': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_3_3),
    'Vehicle': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_4_3),
    'Woodpile': pyautogui.Point(*ui_positions.SUB_MENU_1_4x4_1_4),

    'Object 1': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_1),
    'Object 2': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_1),
    'Object 3': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_1),
    'Object 4': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_2),
    'Object 5': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_2),
    'Object 6': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_2),
    'Object 7': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_1_3),
    'Object 8': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_2_3),
    'Object 9': pyautogui.Point(*ui_positions.SUB_MENU_2_3x4_3_3),
}
